package support;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
/**
 * 
 * @author         :VNatarajan
 * @since          :Sep 20, 2017
 * @filename       :Report.java
 * @version		   :
 * @description    :
 */
public class Report {
	private static Report report;
	static ExtentHtmlReporter testSummary;
	static ExtentReports extent;
	static String reportName;
	public static Report getInstance(){
		if(report==null){
			report= new Report();
			testSummary = new ExtentHtmlReporter("TestSummaryReport.html");
			testSummary.config().setDocumentTitle("Demo App - Report generated by Test Automation");
			testSummary.config().setReportName("Demo App - Report generated by Test Automation");
			extent = new ExtentReports();
			extent.attachReporter(testSummary);
		}
		return report;
	}
	
	/**
	 * 
	 * Method Name : createNewReport
	 * Return Type : ExtentTest
	 * Author      : VNatarajan
	 * Date		   : Sep 20, 2017
	 * Description : Creation of new report for appending test results
	 * @param testId
	 * @param testName
	 * @return
	 */
	
	public synchronized ExtentTest createNewReport(String testId,String testName) {
		ExtentTest test;
		test = extent.createTest(testId, testName);
		return test;
	}
	/**
	 * 
	 * Method Name : closeReport
	 * Return Type : void
	 * Author      : VNatarajan
	 * Date		   : Sep 20, 2017
	 * Description :
	 */
	public synchronized void closeReport() {
		extent.flush();
	}


}
